use [data_health_web]
select * from [dbo].[first_aid_quizz];
delete from [dbo].[first_aid_quizz];
DBCC CHECKIDENT ('[dbo].[first_aid_quizz]', RESEED, 0);

ALTER TABLE [dbo].[first_aid_quizz]
ALTER COLUMN Question NVARCHAR(MAX);


insert into [dbo].[first_aid_quizz] (Question, ImageQuestion, OptionA, OptionB, OptionC, OptionD, TestID, CorrectAnswer)
values 
(N'1. Khi phát hiện người có dấu hiệu đột quỵ, việc đầu tiên cần làm là gì?',
N'https://dichvuxecuuthuong115.com/upload/images/goi-cap-cuu-115.jpg',
N'Cho uống nước đường',
N'Gọi cấp cứu 115 ngay lập tức',
N'Để bệnh nhân tự nghỉ ngơi',
N' Cạo gió cho bệnh nhân',
2,
'B'),
(N'2. Tư thế nằm an toàn nhất cho người nghi ngờ đột quỵ khi chờ cấp cứu là?',
N'https://www.vinmec.com/static/uploads/large_20200424_172336_448622_nghieng_max_1800x1800_jpg_d5092f8f45.jpg',
N'Nằm ngửa, đầu thấp',
N'Ngồi dậy tựa lưng vào tường',
N'Nằm nghiêng một bên, đầu hơi nâng cao',
N'Đứng tựa vào tường',
2,
'C'),
(N'3. Khi sơ cứu đột quỵ, điều nào sau đây là SAI?',
N'https://cdn.nhathuoclongchau.com.vn/unsafe/800x0/https://cms-prod.s3-sgn09.fptcloud.com/nuoc_duong_co_tot_khong_uong_nuoc_duong_co_tac_dung_gi_voi_co_the_2_bb350ce50b.jpg',
N'Nới lỏng quần áo, cà vạt, khăn quàng cổ',
N'Để bệnh nhân ở nơi thoáng mát, thoải mái',
N'Cho bệnh nhân ăn, uống nước đường',
N'Trấn an, nói chuyện nhẹ nhàng với bệnh nhân',
2,
'C'),
(N'4. Dấu hiệu nhận biết nhanh người bị đột quỵ là gì?',
N'https://media.hoiccbvietnam.vn/uploads/2022/12/01/be-fast-1669893523.jpg',
N'Đau bụng dữ dội',
N'Liệt mặt, yếu liệt tay chân, rối loạn ngôn ngữ',
N'Sốt cao, rét run',
N'Đau lưng, buồn nôn',
2,
'B'),
(N'5. Trong khi chờ cấp cứu, cần làm gì để giúp bệnh nhân thở dễ hơn?',
N'https://giadinh.mediacdn.vn/zoom/740_463/2018/6/12/photo-0-15287737059751953704728.jpg',
N'Lau sạch đờm dãi, thức ăn thừa ở miệng, mũi',
N'Cho bệnh nhân uống nước',
N'Để bệnh nhân nằm sấp',
N'Đắp chăn kín đầu',
2,
'A'),
(N'6. Khi sơ cứu đột quỵ, điều nào sau đây là ĐÚNG?',
N'https://cdn.pixabay.com/photo/2017/11/10/13/32/clock-2936333_960_720.png',
N'Ghi nhớ thời điểm khởi phát triệu chứng đột quỵ',
N'Chờ đợi các triệu chứng tự hết rồi mới gọi cấp cứu',
N'Dùng kim chích máu 10 đầu ngón tay',
N'Cho bệnh nhân dùng thuốc hạ huyết áp ngay tại nhà',
2,
'A'),
(N'7. Khi bệnh nhân đột quỵ không còn thở, bạn nên:',
N'https://bvnguyentriphuong.com.vn/uploads/032022/images/th%C6%B0%E1%BB%9Dng%20d%C3%B9ng/ho-hap-nhan-tao-3.jpg',
N'Thực hiện hô hấp nhân tạo hoặc ép tim ngoài lồng ngực nếu biết kỹ thuật',
N'Để bệnh nhân nằm yên, không làm gì',
N'Cho bệnh nhân uống thuốc trợ tim',
N'Đợi nhân viên y tế đến mới làm gì thì làm',
2,
'A'),
(N'8. Trong sơ cứu đột quỵ, việc nào sau đây là SAI hoàn toàn?',
N'https://benh.vn/wp-content/uploads/2018/04/a1.jpg',
N'Không cho bệnh nhân ăn/uống bất cứ thứ gì',
N'Không tự ý cho bệnh nhân dùng thuốc',
N'Không cạo gió, không chích máu đầu ngón tay',
N'Đặt bệnh nhân nằm ngửa, đầu thấp',
2,
'D')