use [data_health_web]
select * from [dbo].[first_aid_test];

insert into [dbo].[first_aid_test]( FirstAidID, Quantity)
values 
(1, 8),
(2, 8)

insert into [dbo].[first_aid_quizz] (Question, ImageQuestion, OptionA, OptionB, OptionC, OptionD, TestID, CorrectAnswer)
values 
(N'Câu 1: Khi phát hiện một người bị nghẹt thở do dị vật, bạn nên làm gì đầu tiên?',
N'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/10/19/heimlich-1-16976836199561662063610.png',
N'Cho nạn nhân uống nước',
N'Thực hiện thao tác giải cứu (Heimlich)',
N'Đặt nạn nhân nằm xuống',
N'Gọi cấp cứu và chờ nhân viên y tế đến',
1,
'B'),
(N'Câu 2: Dấu hiệu nhận biết một người đang bị nghẹt thở do dị vật là gì?',
N'https://nhathuocngocanh.com/wp-content/uploads/2023/06/Hinh-1.-Dau-hieu-nghet-tho-pho-bien.jpg',
N'Nạn nhân ho nhẹ, nói chuyện bình thường',
N'Nạn nhân ôm cổ, không nói chuyện được, không thở được',
N'Nạn nhân ngồi yên, không có biểu hiện gì',
N'Nạn nhân bị sốt cao',
1,
'B'),
(N'Câu 3: Khi thực hiện thủ thuật Heimlich cho người lớn tỉnh táo, bạn cần:',
N'https://cdn.nhathuoclongchau.com.vn/unsafe/800x0/https://cms-prod.s3-sgn09.fptcloud.com/thu_thuat_heimlich_la_gi_cach_thuc_hien_4_f35ed0f809.jpg',
N'Đứng phía trước nạn nhân, dùng hai tay ấn vào ngực',
N'Đứng phía sau nạn nhân, vòng tay qua eo, ấn mạnh vào bụng trên',
N'Đặt nạn nhân nằm ngửa và ấn vào bụng',
N'Để nạn nhân tự xử lý',
1,
'B'),
(N'Câu 4: Nếu nạn nhân bị nghẹt thở nhưng vẫn còn ho được mạnh, bạn nên:',
N'https://img.tripi.vn/cdn-cgi/image/width=700,height=700/https://gcs.tripi.vn/public-tripi/tripi-feed/img/483504bBt/anh-mo-ta.png',
N'Thực hiện ngay thủ thuật Heimlich',
N'Khuyến khích nạn nhân tiếp tục ho mạnh để tống dị vật ra ngoài',
N'Cho nạn nhân uống nước',
N'Đặt nạn nhân nằm xuống',
1,
'B'),
(N'Câu 5: Đối với trẻ nhỏ bị nghẹt thở do dị vật, thao tác sơ cứu phù hợp là:',
N'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn-lZGs1INXBpVl7PNcrGKWY-zW4Hw3GA0cw&s',
N'Vỗ lưng kết hợp ấn ngực',
N'Thực hiện Heimlich như người lớn',
N'Cho trẻ uống nước',
N'Đặt trẻ nằm úp mặt xuống đất',
1,
'A'),
(N'Câu 6: Sau khi dị vật đã được lấy ra, bạn nên làm gì tiếp theo?',
N'https://www.vinmec.com/static/uploads/small_20210104_033217_048064_kiem_tra_nhip_tho_max_1800x1800_png_ab339ce0cf.png',
N'Để nạn nhân tự nghỉ ngơi',
N'Kiểm tra lại đường thở, quan sát tình trạng hô hấp của nạn nhân',
N'Cho nạn nhân ăn uống ngay',
N'Không cần làm gì thêm',
1,
'B'),
(N'Câu 7: Trong trường hợp nạn nhân bị nghẹt thở mất ý thức, bạn nên:',
N'https://suckhoe123.vn/uploads/suc-khoe/2021_05/20200107_063138_982591_tho-oxy.max-1800x1800.png&w=998&h=704&checkress=78e326e34e4f20f4bb25b21076b1a15e',
N'Gọi cấp cứu, tiến hành hồi sức tim phổi (CPR) nếu cần thiết',
N'Để nạn nhân nằm yên chờ nhân viên y tế',
N'Cho nạn nhân uống nước',
N'Đánh mạnh vào lưng nạn nhân',
1,
'A'),
(N'Câu 8: Khi nào bạn nên gọi cấp cứu trong trường hợp nghẹt thở?',
N'https://www.cqscopelab.com/wp-content/uploads/2023/08/image-5.png',
N'Khi dị vật chưa được lấy ra sau các thao tác sơ cứu',
N'Ngay khi phát hiện nạn nhân bị nghẹt thở',
N'Khi nạn nhân có dấu hiệu mất ý thức',
N'Tất cả các trường hợp trên',
1,
'D')
